name: Update VBS

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Create VBS file
      run: |
        echo "Creating VBS file"
        echo "strUrl = \"https://link1.com/dodu\"" > installer.vbs
        echo "VBS file created"
